# Site settings
title: "Source of Thoughts"
description: "Poemas dessa vida e da outra."
poem: "Amor e dor. Alegria e morte.
As palavras por vezes se confundem.
As palavras por vezes nos confundem.
Confundimos as palavras.
Separamos as emoções.
Juntamos tudo novamente.
Eis o ser."
baseurl: ""
url: "http://sourceofthoughts.github.io"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 3

# Links
links:
  - title: "abt us"
    url: /about
  #- title: "twt"
  #  url: http://twitter.com/alixedi
  #- title: "git"
  #  url: http://github.com/candinhojr
  - title: "rss"
    url: /feed.xml
